console.log('Hello World!')
console.log(1)
console.log(true)
console.log({ name: '홍길동', age: 20, married: false })
console.log('로그 - 기본적인 출력')
console.info('로그 - 기능적으로는 log와 같음. 사용하기 에 따라 용도 구분 가능')
console.warn('경고 - 문제가 될 수 있는 부분')
console.error('오류 - 에러 발생 상황')
